// PLACEHOLDER — regenerated by `npm run db:types`
// (`supabase gen types typescript --local > packages/shared/src/database.types.ts`).
//
// This hand-written stub lets the web project type-check offline before the real
// Supabase schema types have been generated. `Database` is intentionally untyped
// (`any`) so the Supabase client's table/insert/select generics resolve
// permissively against a schema that isn't described yet. Running `npm run db:types`
// overwrites this file wholesale with the real, fully-typed schema — do not rely on
// or hand-extend these shapes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// biome-ignore lint/suspicious/noExplicitAny: placeholder schema until `npm run db:types` generates the real one
export type Database = any;
